# Generated by Django 6.0.3 on 2026-03-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_holder',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_number_last4',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expiry_date',
            field=models.CharField(default='00/00', max_length=7),
        ),
    ]
