# Generated by Django 6.0.1 on 2026-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_card_holder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingData',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('card_number_last4', models.CharField(max_length=4)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('is_fraud', models.BooleanField()),
            ],
            options={
                'db_table': 'ml_training_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('device_type', models.CharField(default='Unknown', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.IntegerField(blank=True, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious')], default='safe', max_length=20)),
                ('user_response', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
            ],
        ),
    ]
