# Generated by Django 6.0.1 on 2026-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mltrainingdata_livetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingDataIndia',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('card_number_last4', models.CharField(max_length=4)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('is_fraud', models.BooleanField()),
            ],
            options={
                'db_table': 'ml_training_data_india',
            },
        ),
        migrations.DeleteModel(
            name='MLTrainingData',
        ),
    ]
